### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Trott** [wafflejs/incident#2]
Can I persuade you to add a license file so that the terms under which this can be repurposed are clear?

**Comment by MylesBorins** [comment]
how do peeps feel about MIT?

**Comment by visnup** [comment]
I could go even looser. like Public Domain or whatevs.

**Comment by MylesBorins** [comment]
So gpl?

**Comment by dshaw** [comment]
MIT, please. Public Domain or wtfpl are problematic for larger legal departments.
